import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navber/page";
import Footer from "./Footer/page";
import AuthProvider, { Countnumber } from "./context/AuthContext"; // এই লাইন যোগ করুন

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" suppressHydrationWarning>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
         
        <AuthProvider>  
          <Navbar />
          <main className="flex-1">
            {children}
          </main>
          <Footer />
        </AuthProvider>  
         
      </body>
    </html>
  );
}